{{- if .Values.supavisor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.supavisor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.supavisor.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.supavisor.service.type }}
  ports:
    - port: {{ include "supabase.database.port" . | int }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
    - port: {{ .Values.supavisor.service.port }}
      targetPort: 6543
      protocol: TCP
      name: pooler
  selector:
    {{- include "supabase.supavisor.selectorLabels" . | nindent 4 }}
{{- end }}
