{{- if .Values.rest.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.rest.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.rest.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.rest.autoscaling.enabled }}
  replicas: {{ .Values.rest.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.rest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.rest.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.rest.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.rest.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.rest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.rest.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "supabase.waitForDB" . | nindent 8 }}
      containers:
        - name: {{ include "supabase.rest.name" $ }}
          securityContext:
            {{- toYaml .Values.rest.securityContext | nindent 12 }}
          image: "{{ .Values.rest.image.repository }}:{{ .Values.rest.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rest.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.rest.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DB_HOST
              value: {{ include "supabase.database.host" . | quote }}
            - name: DB_PORT
              value: {{ include "supabase.database.port" . | quote }}
            - name: DB_SSL_MODE
              value: {{ include "supabase.database.sslmode" . | quote }}
            - name: DB_USERNAME
              value: {{ include "supabase.database.rest_username" . | quote }}
            - name: DB_PASSWORD
              {{- include "supabase.database.password" . | nindent 14 }}
            - name: DB_NAME
              value: {{ include "supabase.database.db_name" . | quote }}
            - name: PGRST_DB_URI
              value: postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL_MODE)
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}
            - name: PGRST_APP_SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}
          {{- with .Values.rest.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.rest.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.rest.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.rest.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.rest.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rest.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rest.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rest.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
